### ISSUE TITLE
Split out "Drupal parity" into new module.

### ISSUE THREAD

**Issue by mglaman** [druxt/druxt.js#13]
**Is your feature request related to a problem? Please describe.**
We'd like to use druxt.js, but not all of the modules.

Currently we're forced to use them all per https://github.com/druxt/druxt.js/blob/develop/src/module.js#L30

```
  // Add NuxtJS modules.
  const modules = [
    '@nuxtjs/proxy',
    'druxt-blocks',
    'druxt-breadcrumb',
    'druxt-entity',
    'druxt-menu',
    'druxt-router',
    'druxt-schema',
    'druxt-search',
    'druxt-views'
  ]
  for (const key in modules) {
    this.addModule(modules[key])
  }
```

**Describe the solution you'd like**
I'd like druxt.js to just work with what modules we define.

**Describe alternatives you've considered**
Hacking the code in node_modules

**Additional context**
druxt-schema does not work with aliased resource types. So the alternative is to not use schema or entity modules.

**Comment by wonder95** [comment]
My thought is that you could add an `modules` item to the `options` key in `nuxt.config.js`, and then modify `DruxtModule()` like so:
```
for (const key in options.modules) {
  this.addModule(options.modules[key]
}
```

**Comment by Decipher** [comment]
Hi @mglaman / @wonder95,

You can already use DruxtJS without all the modules, you just need to install the modules individually instead of installing the meta module.

However, the suggestion to have them configurable is very appealing, so I’m happy to proceed with a solution like that.

With regards to the Druxt Schema and aliased resources, there is an open issue with code available at https://github.com/druxt/druxt-schema/issues/6

**Comment by Decipher** [comment]
As per a Slack discussion with @wonder95, a working example of how to just use the `druxt-menu` module by itself can be found here: https://github.com/Decipher/druxt-menu-example

**Comment by mglaman** [comment]
@Decipher great! so there's nothing _too_ fancy for the store.

Maybe we can have a repo in the org for an "awesome-druxt" list and "druxt-contrib"

Totally ripping this from https://github.com/drud/awesome-ddev and https://github.com/drud/ddev-contrib.

**Comment by Decipher** [comment]
> so there's nothing _too_ fancy for the store.

Yeah, NuxtJS only initialises the Vuex store if you have atleast one module present. But the DruxtJS module specifically turns the feature on.

Each individual module that has a Vuex store should also be doing this, I will follow that up in in the future.

And absolutely intend to have `awesome-druxt`.

**Comment by Decipher** [comment]
I'm revisiting this issue, as Druxt `0.3.0` is going to be bing in a new `Druxt` component that will become the core of this module.

As such, the requirements to create a parity Drupal application should be shifted into it's own module.

**Comment by Decipher** [comment]
The DruxtJS Site module now lives, which will now be the base module for anyone using Druxt to do a fully decoupled "Site".

This functionality will be deprecated from the DruxtJS module, along with a bunch of new core improvements, in an upcoming release.

**Comment by Decipher** [comment]
The site specific functionality now lives in [Druxt Site](https://site.druxtjs.org), and the Druxt module now provides a Druxt component to provide a connection to the relevant module.

You can find more details at https://druxtjs.org
