### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by CarmelClark** [druxt/druxt.js#158]
**Is your feature request related to a problem? Please describe.**
There is no support for the multilingual content provided by the Umami demo.

**Describe the solution you'd like**
- [x] DruxtClient support for prefixes or langcodes
  - A node application should be able to request any resource by langcode with a fallback default langcode.
  - [x] createResource (untested)
  - [x] getCollection
  - [x] getCollectionAll
  - [x] getIndex
  - [x] getRelated
  - [x] getResource
  - [x] updateResource (untested)
- [ ] Druxt modules support
  - [x] DruxtBlock
    - [x] DruxtBlockRegion isVisible method needs to support prefixes
  - [x] DruxtBreadcrumb
  - [x] DruxtEntity needs a **langcode** prop.
  - [ ] DruxtMenu
    - [x] DruxtMenu needs a **langcode** prop.
    - [x] DruxtMenu store needs support for **prefix**.
    - [ ] JSON:API Menu Items needs **langcode** support:
      - [ ] https://www.drupal.org/project/jsonapi_menu_items/issues/3192576
      - [ ] https://www.drupal.org/project/jsonapi_menu_items/issues/3260494
  - [ ] DruxtView
    - [x] DruxtView needs a **langcode** prop.
    - [ ] JSON:API Views needs multilingual support in Decoupled Router integration: https://www.drupal.org/project/druxt/issues/3273228
- [x] DruxtStore support for prefixes or langcodes
  - [x] druxt/addResource; resource data is stored against prefix
  - [x] druxt/getResource
  - [x] addCollection
  - [x] getCollection
- [ ] DruxtRouter support for prefixes or langcodes
  - Fetching the route shouldn't need to change, nor should the storage, as the langcode data is provided by the Decoupled Router with patch
    ```
    "drupal/decoupled_router": {
      "https://www.drupal.org/project/decoupled_router/issues/3111456#comment-14093342": "https://www.drupal.org/files/issues/2021-05-05/3111456-34.patch"
    }
    ```
  - [x] Redirects need to work
    - Workaround: Disable router middleware
  - [x] API proxy endpoint for langcode prefixes

**Testing (in gitpod)**
1. Open https://gitpod.io/#https://github.com/druxt/druxt.js/pull/422
2. Wait
3. `cd examples/nuxt/druxt-site && yarn && yarn dev`

**Describe alternatives you've considered**
No

**Additional context**
- Multilingual enabled backend: https://nginx.develop.demo-api-druxtjs-org.au2.amazee.io
- https://github.com/robedwards-cti/druxt.js/commit/b89857e2d5a9a9d76a2ba4b93fb8c8eca74f5139

- ![image](https://user-images.githubusercontent.com/69707846/93947597-7abb7180-fd7f-11ea-902c-15122d8c82aa.png)
- https://demo-api.druxtjs.org/es
- https://demo.druxtjs.org/es (redirects to English).
- https://demo-api.druxtjs.org/en/jsonapi/configurable_language/configurable_language

**Comment by Decipher** [comment]
Looks like you can get a translated version of the entire site (mostly) just by changing the endpoint in the `nuxt.js.config`:

```js
export default {
  ...
  druxt: {
    baseUrl: 'https://demo-api.druxtjs.org',
    endpoint: '/es/jsonapi'
  }
}
```

![image](https://user-images.githubusercontent.com/161090/137795967-1c3357fc-2f87-4e01-8480-8bb3c21da2f1.png)

**Comment by Decipher** [comment]
I believe that all Druxt functional changes have been made.
It's now just a case of updating the test coverage by adding more automated tests, and ensuring the documentation is correct.
