### ISSUE TITLE
Allow application of settings to a module component when not using wrapper

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/druxt.js#356]
**Is your feature request related to a problem? Please describe.**
There is currently no way to apply settings when not using a wrapper

**Describe the solution you'd like**
```
<DruxtEntity :mode="mode" :uuid="uuid" :type="type" :settings="{ query: { fields: ['title'] } }" :wrapper="false" />
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Decipher** [comment]
This was resolved in #355
