### ISSUE TITLE
Add support for Cyprus front-end testing tool.

### ISSUE THREAD

**Issue by captaindav** [druxt/druxt.js#527]
**Is your feature request related to a problem? Please describe.**
Improve the quality of Druxt code by using automated testing.

**Describe the solution you'd like**
As a developer I would like to use Cyprus to test code as it is being pushed and also as part of the build process.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Decipher** [comment]
Hi @captaindav,

This issue already exists @ #92
